version: "3.8"
services:
  candy-machine-factory:
    container_name: candy-machine-factory
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "${PORT}:${PORT}"
    expose:
      - "${PORT}"